export const users = [
  {
    id: 1,
    username: "admin",
    email: "admin@vroom.com",
    password:
      "$argon2id$v=19$m=65536,t=3,p=4$DDXkvDxw3PNiSIg8/cn67g$m/GhPrYzwGOUidcSPJ8XnmB0OUHAw9quzdMDyJIT30Y",
    profile_picture: "person_15439869.png",
    firstname: "admin",
    lastname: "admin",
    birthdate: "1990-01-01",
    phone_number: "+33601020304",
    sold: 100,
    is_admin: true,
  },
  {
    id: 2,
    username: "Aldup",
    email: "alice@example.com",
    password:
      "$argon2id$v=19$m=65536,t=3,p=4$DDXkvDxw3PNiSIg8/cn67g$m/GhPrYzwGOUidcSPJ8XnmB0OUHAw9quzdMDyJIT30Y",
    profile_picture: "person_15439869.png",
    firstname: "Alice",
    lastname: "Dupont",
    birthdate: "2001-01-01",
    phone_number: "+33601020304",
    sold: 2,
    is_admin: false,
  },
  {
    id: 3,
    username: "The B",
    email: "bob@example.com",
    password:
      "$argon2id$v=19$m=65536,t=3,p=4$DDXkvDxw3PNiSIg8/cn67g$m/GhPrYzwGOUidcSPJ8XnmB0OUHAw9quzdMDyJIT30Y",
    profile_picture: "person_15439869.png",
    firstname: "Bob",
    lastname: "Martin",
    birthdate: "2001-01-01",
    phone_number: "+33601020311",
    sold: 1,
    is_admin: false,
  },
];

export const christmasMarkets = [
  {
    name: "Marché de Noël de Strasbourg",
    location: { x: 48.583148, y: 7.747882 },
    address: "Place de la Cathédrale, 67000 Strasbourg",
    number_of_exponents: 300,
    number_of_craftsmen: 150,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "parade"],
    animals_forbidden: false,
    exposition: true,
    santa_present: true,
    restauration: "both" as const,
    usual_days: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    user_id: 1,
  },
  {
    name: "Marché de Noël de Colmar",
    location: { x: 48.079358, y: 7.358512 },
    address: "Place des Dominicains, 68000 Colmar",
    number_of_exponents: 200,
    number_of_craftsmen: 100,
    place_type: "church" as const,
    animation_type: ["food", "music"],
    animals_forbidden: true,
    exposition: false,
    santa_present: true,
    restauration: "food" as const,
    usual_days: ["Friday", "Saturday", "Sunday"],
    user_id: 1,
  },
  {
    name: "Marché de Noël de Paris",
    location: { x: 48.8738, y: 2.295 },
    address: "Champs-Élysées, 75008 Paris",
    number_of_exponents: 100,
    number_of_craftsmen: 500,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "parade"],
    animals_forbidden: false,
    exposition: true,
    santa_present: true,
    restauration: "both" as const,
    usual_days: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    user_id: 1,
  },
  {
    name: "Marché de Noël de Lyon",
    location: { x: 45.764, y: 4.8357 },
    address: "Place Carnot, 69002 Lyon",
    number_of_exponents: 120,
    number_of_craftsmen: 250,
    place_type: "main_square" as const,
    animation_type: ["music", "parade"],
    animals_forbidden: false,
    exposition: true,
    santa_present: true,
    restauration: "food" as const,
    usual_days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    user_id: 1,
  },
  {
    name: "Marché de Noël de Lille",
    location: { x: 50.6292, y: 3.0573 },
    address: "Grand Place, 59000 Lille",
    number_of_exponents: 200,
    number_of_craftsmen: 450,
    place_type: "main_square" as const,
    animation_type: ["food", "drink"],
    animals_forbidden: true,
    exposition: true,
    santa_present: true,
    restauration: "both" as const,
    usual_days: ["Wednesday", "Thursday", "Friday", "Saturday"],
    user_id: 1,
  },
];
