// server/src/database/seedData.ts
export const users = [
  {
    id: 1,
    username: "admin",
    email: "admin@vroom.com",
    password:
      "$argon2id$v=19$m=65536,t=3,p=4$DDXkvDxw3PNiSIg8/cn67g$m/GhPrYzwGOUidcSPJ8XnmB0OUHAw9quzdMDyJIT30Y",
    profile_picture: "person_15439869.png",
    firstname: "admin",
    lastname: "admin",
    birthdate: "1990-01-01",
    phone_number: "+33601020304",
    sold: 100,
    is_admin: true,
  },
  {
    id: 2,
    username: "Aldup",
    email: "alice@example.com",
    password:
      "$argon2id$v=19$m=65536,t=3,p=4$DDXkvDxw3PNiSIg8/cn67g$m/GhPrYzwGOUidcSPJ8XnmB0OUHAw9quzdMDyJIT30Y",
    profile_picture: "person_15439869.png",
    firstname: "Alice",
    lastname: "Dupont",
    birthdate: "2001-01-01",
    phone_number: "+33601020304",
    sold: 2,
    is_admin: false,
  },
  {
    id: 3,
    username: "The B",
    email: "bob@example.com",
    password:
      "$argon2id$v=19$m=65536,t=3,p=4$DDXkvDxw3PNiSIg8/cn67g$m/GhPrYzwGOUidcSPJ8XnmB0OUHAw9quzdMDyJIT30Y",
    profile_picture: "person_15439869.png",
    firstname: "Bob",
    lastname: "Martin",
    birthdate: "2001-01-01",
    phone_number: "+33601020311",
    sold: 1,
    is_admin: false,
  },
];

export const christmasMarkets = [
  // Nord-Pas-de-Calais - France
  {
    name: "Lille Christmas Market",
    location: { x: 50.6292, y: 3.0573 },
    address: "Grand Place, 59000 Lille, France",
    number_of_exponents: 180,
    number_of_craftsmen: 90,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "ice_skating"],
    animals_forbidden: true,
    exposition: true,
    santa_present: true,
    restauration: "both" as const,
    usual_days: ["Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    user_id: 1,
  },
  {
    name: "Arras Christmas Market",
    location: { x: 50.291, y: 2.7775 },
    address: "Grand Place, 62000 Arras, France",
    number_of_exponents: 120,
    number_of_craftsmen: 60,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "crafts"],
    animals_forbidden: false,
    exposition: true,
    santa_present: true,
    restauration: "food" as const,
    usual_days: ["Friday", "Saturday", "Sunday"],
    user_id: 1,
  },
  {
    name: "Dunkerque Christmas Market",
    location: { x: 51.0344, y: 2.3768 },
    address: "Place Jean Bart, 59140 Dunkerque, France",
    number_of_exponents: 80,
    number_of_craftsmen: 40,
    place_type: "main_square" as const,
    animation_type: ["food", "music"],
    animals_forbidden: true,
    exposition: false,
    santa_present: false,
    restauration: "both" as const,
    usual_days: ["Saturday", "Sunday"],
    user_id: 1,
  },
  {
    name: "Calais Christmas Market",
    location: { x: 50.9513, y: 1.8587 },
    address: "Place d'Armes, 62100 Calais, France",
    number_of_exponents: 90,
    number_of_craftsmen: 45,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "parade"],
    animals_forbidden: false,
    exposition: true,
    santa_present: true,
    restauration: "food" as const,
    usual_days: ["Thursday", "Friday", "Saturday", "Sunday"],
    user_id: 1,
  },
  {
    name: "Boulogne-sur-Mer Christmas Market",
    location: { x: 50.7256, y: 1.6139 },
    address: "Place Dalton, 62200 Boulogne-sur-Mer, France",
    number_of_exponents: 70,
    number_of_craftsmen: 35,
    place_type: "main_square" as const,
    animation_type: ["food", "crafts"],
    animals_forbidden: true,
    exposition: false,
    santa_present: true,
    restauration: "drink" as const,
    usual_days: ["Friday", "Saturday"],
    user_id: 1,
  },

  // Hauts-de-France - France
  {
    name: "Amiens Christmas Market",
    location: { x: 49.8941, y: 2.2958 },
    address: "Place de l'Hôtel de Ville, 80000 Amiens, France",
    number_of_exponents: 150,
    number_of_craftsmen: 75,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "light_show"],
    animals_forbidden: false,
    exposition: true,
    santa_present: true,
    restauration: "both" as const,
    usual_days: [
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    user_id: 1,
  },
  {
    name: "Roubaix Christmas Market",
    location: { x: 50.6901, y: 3.1817 },
    address: "Grand Place, 59100 Roubaix, France",
    number_of_exponents: 60,
    number_of_craftsmen: 30,
    place_type: "main_square" as const,
    animation_type: ["food", "crafts"],
    animals_forbidden: true,
    exposition: false,
    santa_present: false,
    restauration: "food" as const,
    usual_days: ["Saturday", "Sunday"],
    user_id: 1,
  },
  {
    name: "Tourcoing Christmas Market",
    location: { x: 50.7239, y: 3.1612 },
    address: "Place de la Victoire, 59200 Tourcoing, France",
    number_of_exponents: 55,
    number_of_craftsmen: 28,
    place_type: "main_square" as const,
    animation_type: ["food", "music"],
    animals_forbidden: false,
    exposition: true,
    santa_present: true,
    restauration: "both" as const,
    usual_days: ["Friday", "Saturday", "Sunday"],
    user_id: 1,
  },

  // Wallonia - Belgium
  {
    name: "Brussels Christmas Market",
    location: { x: 50.8503, y: 4.3517 },
    address: "Grand Place, 1000 Brussels, Belgium",
    number_of_exponents: 250,
    number_of_craftsmen: 120,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "ice_skating", "ferris_wheel"],
    animals_forbidden: false,
    exposition: true,
    santa_present: true,
    restauration: "both" as const,
    usual_days: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    user_id: 1,
  },
  {
    name: "Mons Christmas Market",
    location: { x: 50.4542, y: 3.956 },
    address: "Grand Place, 7000 Mons, Belgium",
    number_of_exponents: 110,
    number_of_craftsmen: 55,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "crafts"],
    animals_forbidden: true,
    exposition: true,
    santa_present: true,
    restauration: "both" as const,
    usual_days: ["Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    user_id: 1,
  },
  {
    name: "Tournai Christmas Market",
    location: { x: 50.6056, y: 3.388 },
    address: "Grand Place, 7500 Tournai, Belgium",
    number_of_exponents: 85,
    number_of_craftsmen: 42,
    place_type: "main_square" as const,
    animation_type: ["food", "music"],
    animals_forbidden: false,
    exposition: false,
    santa_present: true,
    restauration: "food" as const,
    usual_days: ["Friday", "Saturday", "Sunday"],
    user_id: 1,
  },
  {
    name: "Charleroi Christmas Market",
    location: { x: 50.4108, y: 4.4448 },
    address: "Place Charles II, 6000 Charleroi, Belgium",
    number_of_exponents: 95,
    number_of_craftsmen: 48,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "parade"],
    animals_forbidden: true,
    exposition: true,
    santa_present: false,
    restauration: "both" as const,
    usual_days: ["Thursday", "Friday", "Saturday", "Sunday"],
    user_id: 1,
  },
  {
    name: "Namur Christmas Market",
    location: { x: 50.4674, y: 4.8718 },
    address: "Place d'Armes, 5000 Namur, Belgium",
    number_of_exponents: 130,
    number_of_craftsmen: 65,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "ice_skating"],
    animals_forbidden: false,
    exposition: true,
    santa_present: true,
    restauration: "both" as const,
    usual_days: [
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    user_id: 1,
  },

  // Flanders - Belgium
  {
    name: "Ghent Christmas Market",
    location: { x: 51.0543, y: 3.7174 },
    address: "Sint-Baafsplein, 9000 Ghent, Belgium",
    number_of_exponents: 180,
    number_of_craftsmen: 90,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "ice_skating", "crafts"],
    animals_forbidden: false,
    exposition: true,
    santa_present: true,
    restauration: "both" as const,
    usual_days: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    user_id: 1,
  },
  {
    name: "Bruges Christmas Market",
    location: { x: 51.2093, y: 3.2247 },
    address: "Markt, 8000 Bruges, Belgium",
    number_of_exponents: 160,
    number_of_craftsmen: 80,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "ice_skating"],
    animals_forbidden: true,
    exposition: true,
    santa_present: true,
    restauration: "both" as const,
    usual_days: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    user_id: 1,
  },
  {
    name: "Antwerp Christmas Market",
    location: { x: 51.2194, y: 4.4025 },
    address: "Grote Markt, 2000 Antwerp, Belgium",
    number_of_exponents: 200,
    number_of_craftsmen: 100,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "ferris_wheel", "ice_skating"],
    animals_forbidden: false,
    exposition: true,
    santa_present: true,
    restauration: "both" as const,
    usual_days: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    user_id: 1,
  },
  {
    name: "Leuven Christmas Market",
    location: { x: 50.8792, y: 4.7012 },
    address: "Grote Markt, 3000 Leuven, Belgium",
    number_of_exponents: 120,
    number_of_craftsmen: 60,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "crafts"],
    animals_forbidden: true,
    exposition: false,
    santa_present: true,
    restauration: "both" as const,
    usual_days: ["Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    user_id: 1,
  },
  {
    name: "Mechelen Christmas Market",
    location: { x: 51.0277, y: 4.4804 },
    address: "Grote Markt, 2800 Mechelen, Belgium",
    number_of_exponents: 90,
    number_of_craftsmen: 45,
    place_type: "main_square" as const,
    animation_type: ["food", "music"],
    animals_forbidden: false,
    exposition: true,
    santa_present: false,
    restauration: "food" as const,
    usual_days: ["Friday", "Saturday", "Sunday"],
    user_id: 1,
  },

  // Additional French markets
  {
    name: "Valenciennes Christmas Market",
    location: { x: 50.3576, y: 3.5233 },
    address: "Place d'Armes, 59300 Valenciennes, France",
    number_of_exponents: 75,
    number_of_craftsmen: 38,
    place_type: "main_square" as const,
    animation_type: ["food", "crafts"],
    animals_forbidden: true,
    exposition: false,
    santa_present: true,
    restauration: "drink" as const,
    usual_days: ["Saturday", "Sunday"],
    user_id: 1,
  },
  {
    name: "Douai Christmas Market",
    location: { x: 50.37, y: 3.079 },
    address: "Place d'Armes, 59500 Douai, France",
    number_of_exponents: 65,
    number_of_craftsmen: 32,
    place_type: "main_square" as const,
    animation_type: ["food", "music"],
    animals_forbidden: false,
    exposition: true,
    santa_present: false,
    restauration: "both" as const,
    usual_days: ["Friday", "Saturday"],
    user_id: 1,
  },
  {
    name: "Cambrai Christmas Market",
    location: { x: 50.1755, y: 3.2346 },
    address: "Place Aristide Briand, 59400 Cambrai, France",
    number_of_exponents: 50,
    number_of_craftsmen: 25,
    place_type: "main_square" as const,
    animation_type: ["food"],
    animals_forbidden: true,
    exposition: false,
    santa_present: true,
    restauration: "food" as const,
    usual_days: ["Saturday"],
    user_id: 1,
  },

  // Additional Belgian markets
  {
    name: "Ypres Christmas Market",
    location: { x: 50.8514, y: 2.8855 },
    address: "Grote Markt, 8900 Ypres, Belgium",
    number_of_exponents: 70,
    number_of_craftsmen: 35,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "crafts"],
    animals_forbidden: false,
    exposition: true,
    santa_present: true,
    restauration: "both" as const,
    usual_days: ["Friday", "Saturday", "Sunday"],
    user_id: 1,
  },
  {
    name: "Kortrijk Christmas Market",
    location: { x: 50.828, y: 3.2648 },
    address: "Grote Markt, 8500 Kortrijk, Belgium",
    number_of_exponents: 85,
    number_of_craftsmen: 42,
    place_type: "main_square" as const,
    animation_type: ["food", "music"],
    animals_forbidden: true,
    exposition: false,
    santa_present: false,
    restauration: "food" as const,
    usual_days: ["Thursday", "Friday", "Saturday", "Sunday"],
    user_id: 1,
  },
  {
    name: "Ostend Christmas Market",
    location: { x: 51.2312, y: 2.9126 },
    address: "Wapenplein, 8400 Ostend, Belgium",
    number_of_exponents: 95,
    number_of_craftsmen: 48,
    place_type: "main_square" as const,
    animation_type: ["food", "music", "ice_skating"],
    animals_forbidden: false,
    exposition: true,
    santa_present: true,
    restauration: "both" as const,
    usual_days: ["Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    user_id: 1,
  },
];
